server:
  port: 8080
#  ssl:
#    key-store: classpath:server.jks
#    key-store-password: tPrBlON7
#    key-store-type: JKS

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_boot_demo
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

jwt:
  secret: springbootdemo_jwt_secret
  expiration: 3600

qiniu:
  accessKey: wdoVNp9qXmswTakEjVcfFEqdi0JebQi8tNLDxMJg
  secretKey: Jmool8zj8njyMlVOX_zduoZgb_2ssqBO9V3sy-XH
  bucket: boredream-files
  uploadHost: http://up.qiniu.com/
  downloadHost: http://r0p1o4yza.hd-bkt.clouddn.com/

