server:
  port: 8080
  servlet:
    context-path: /api

#logging:
#  file:
#    name: springboot.log

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sep_talk
    username: sep
    password: aDmbKmMLBZpGyWEK
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: localhost
    password: root

jwt:
  secret: springbootdemo_jwt_secret
  expiration: 30 # day

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml  # 自定义xml文件路径
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

qiniu:
  accessKey: wdoVNp9qXmswTakEjVcfFEqdi0JebQi8tNLDxMJg
  secretKey: Jmool8zj8njyMlVOX_zduoZgb_2ssqBO9V3sy-XH
  bucket: sep-talk
  uploadHost: https://upload.qiniup.com/
  downloadHost: https://sep-talk.s3.cn-east-1.qiniucs.com/
