server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_boot_demo
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

jwt:
  secret: springbootdemo_jwt_secret
  expiration: 30 # day

qiniu:
  accessKey: wdoVNp9qXmswTakEjVcfFEqdi0JebQi8tNLDxMJg
  secretKey: Jmool8zj8njyMlVOX_zduoZgb_2ssqBO9V3sy-XH
  bucket: boredream-files
  uploadHost: https://upload.qiniup.com/
  downloadHost: https://file.papikoala.cn/

