version: "3.9"
services:
  nginx:
    image: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes: # 宿主机目录:容器目录
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # 配置
      - ./nginx/log:/var/log/nginx  # 日志
      - ./nginx/html:/usr/share/nginx/html  # 网页
      - ./nginx/cert:/etc/nginx/cert  # ssl

  mysql:
    image: mysql:8.0.26
    restart: always
    environment: # 环境变量配置去 https://hub.docker.com/_/mysql 官方查看
      MYSQL_ROOT_PASSWORD: "root" # root账号密码
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql # 数据
      - ./mysql/conf:/etc/mysql # 配置
      - ./mysql/log:/var/log/mysql # 日志
      - ./mysql/init:/docker-entrypoint-initdb.d # mysql第一次启动时执行,之后重启容器不会重复执行

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
    command: redis-server --requirepass root
    privileged: true